/** Declaration file generated by dts-gen */

/*~ Note that ES6 modules cannot directly export class objects.
 *~ This file should be imported using the CommonJS-style:
 *~   import x = require('someLibrary');
 *~
 *~ Refer to the documentation to understand common
 *~ workarounds for this limitation of ES6 modules.
 */

/*~ If this module is a UMD module that exposes a global variable 'DynamoDBCRILib' when
 *~ loaded outside a module loader environment, declare that global here.
 *~ Otherwise, delete this declaration.
 */
export as namespace DynamoDBCRILib;

/*~ This declaration specifies that the class constructor function
 *~ is the exported object from the file
 */
export = DynamoDBCRI;

/*~ Write your module's methods and properties in this class */
declare class DynamoDBCRI {
  constructor();
}

/*~ If you want to expose types from your module as well, you can
 *~ place them in this block.
 */
declare namespace DynamoDBCRI {

}
